# Generated by Django 3.2 on 2021-06-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPlaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dish_def', models.CharField(max_length=30)),
                ('Item_name', models.CharField(max_length=40)),
                ('Price', models.IntegerField()),
                ('Confectionary', models.BooleanField(default=False)),
            ],
        ),
    ]
